### ISSUE TITLE
"Notify für folgende Rufnummern aktivieren" is ignored for outgoing calls 

### ISSUE THREAD

**Issue by martini** [Placetel/call-control-notify-api#19] opened 2019-12-30 14:15 UTC
**Usecase:**

I use Zammad with placetel control notify api to show my caller log in Zammad. I have many phone devices in my company and 2 phone devices in my support department. I the caller log I only want to see my 2 support related phone devices (because I dont want to see sales activity an other stuff).

**Problem:**
I only activated the 2 support phone numbers in the placetel admin interface -> 
Weitere Einstellungen -> APIs -> externe APIs -> Notify für folgende Rufnummern aktivieren

But placetel always pushs all putbound call informations of any phone device (even all sales acitvity) to Zammad.

**Solution:**
Only push call informations for checked numbers in "Notify für folgende Rufnummern aktivieren"

**Comment by MrGeneration** [comment] 2019-12-30 19:32
For context, here's a screencast that actually shows the issue we believe to have found:

![zammad-cti-placetel_outgoing-api](https://user-images.githubusercontent.com/6549061/71597339-0ed71000-2b43-11ea-9c89-a424a66cb72f.gif)

Incoming data is highlighted (as soon as it arrives) on the UI for the ease of recognition.
During the first try, you'll see us calling out to any number without selected extensions `0*` and `00*`.

During the second try you'll see how the Notify-API behaves when having selected the extensions `0*` and `00*`.

`*` Please note: Extension `0` is configured as default outgoing number - the caller is part of this configuration (and also member of the call group that's assigned to it).

`99` is the fax extension which we ignored (but shouldn't really count).

**Comment by felixtriller** [comment] 2020-01-06 09:17
Hi @MrGeneration and @martini

right now, this is the intended behavior and stated in the [documentation](https://github.com/Placetel/call-control-notify-api/blob/master/README.md#setup):
> Currently there are notifications for all outgoing calls.

We will discuss our options here and I will come back to you!

**Comment by MrGeneration** [comment] 2020-01-15 09:20
We just received Feedback from our customer that your customer support states that Zammad (the software the customer uses) should interpret the information better and decide which information shall be shown within the UI.

However, the configuration UI of placetel API is missleading in this regard.
Zammad itself does not qualify is this is a filtered user or not.

I'm a bit puzzled right now, this might go into the wrong direction right now.

**Comment by felixtriller** [comment] 2020-01-15 09:35
@MrGeneration as we already told our customer: we are working on it.

The problem here is that outbound calls don't need to be tied to a phone number at Placetel. When limiting outbound notifications to phone numbers, there will be no way to get notified about calls made by a VoIP user with a caller ID set to anonymous, for example.

Again, we will figure out a solution.

**Comment by felixtriller** [comment] 2020-02-13 09:26
@MrGeneration we made the following change: Outgoing calls are only notified if the caller ID of the used SIP user is set and the used number is enabled for notifications.

**Closed by felixtriller** 2020-02-13 09:26 UTC

**Comment by MrGeneration** [comment] 2020-02-13 10:34
Amazing news - thank you very much for your effort! :)
